services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: docker-presentation/nginx
    container_name: nginx-loadbalancer
    ports:
      - "5000:5000"
    networks:
      - api-network
    depends_on:
      - "api-1"
      - "api-2"

  api-1:
    build:
      dockerfile: ./docker/python.dockerfile
      context: .
    image: docker-presentation/api
    container_name: api-1
    ports:
      - "5000"
    networks:
      - api-network
    depends_on:
      - "db"

  api-2:
    build:
      dockerfile: ./docker/python.dockerfile
      context: .
    image: docker-presentation/api
    container_name: api-2
    ports:
      - "5000"
    networks:
      - api-network
    depends_on:
      - "db"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - api-network

volumes:
  postgres_data:

networks:
  api-network:
    driver: bridge
